### ISSUE TITLE
what should input/seed.in look like?

### ISSUE THREAD

**Issue by cboettig** [iskanderun/NetGen#2]
Looks like I need an `input/seed.in` file to initialize the random number generator? I get the error on execution: 

```
At line 57 of file FortranNetGen.f90 (unit = 50, file = './input/seed.in')
Fortran runtime error: End of file
```

Thanks!

**Comment by iskanderun** [comment]
I've run into this problem before, and I believe what you need to do is save the code as a .py file to a local directory, and then run it from an environment that has graphics capabilities. Try CanoPy, for example. Let me know if that resolves it.

**Comment by cboettig** [comment]
hmm... I'm running it from R, guess I should have tried that first.  Do you have an example `input/seed.in` laying around that I can compare against?

**Comment by cboettig** [comment]
Hi Erica, 

sorry to bug you, just wondering if you heard back from your colleague about the fortran code?  I'm able to run the code, but not getting the expected output.  I see:


```
      module size     module type
 ----------------------------------------- 
 ----------------------------------------- 
 average degree =              NaN
 average module size =              NaN
 number of components =           0
 size of largest component =           0

 WARNING: THE NETWORK HAS MORE THAN ONE CONNECTED COMPONENT
 RUN THE PROGRAM AGAIN UNTIL A SINGLE COMPONENT IS OBTAINED
 TRY INCREASING THE REWIRING PROBABILIES

 ----------------------------------------- 
```

using the defaults provided.

**Comment by iskanderun** [comment]
Hey Carl- I'm going to send you the updated package directly and update Git next week when I have time to do the documentation part.

**Comment by cboettig** [comment]
@iskanderun thanks Erica!
